### ISSUE TITLE
CEQR Air Quality: Major or large emission source

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#13]
‘Major or large emission source’
Inputs:
[Title V State Permits 
](https://data.ny.gov/Energy-Environment/Issued-Title-V-Facility-Permits/4n3a-en4b)
[Facility State Permits
](https://data.ny.gov/Energy-Environment/Issued-State-Facility-Air-Permits/2wgt-bc53)

Steps:
- [x] load to recipes
- [x] Geocode
- [x] Merge
- [x] Deduplicate

Odor-producing facilities are included in these data

**Comment by AmandaDoyle** [comment]
Reopening so that we can QAQC dataset:
- [x] Check locations against DEC website https://gisservices.dec.ny.gov/gis/dil/
- [x] Check against what Cary shared
- [ ] If it looks good then send to Adrien to put on M drive and share these data with Lynn
- [ ] These are datasets we'll want to update quarterly so make sure pipes flow

**Comment by baolingz** [comment]
**Comparison between Carey's file and the output generated by open data**
1. Carey's shapefiles have been joined with PLUTO on bbl, which can be incorporated into our workflow as well. Only the facility address is provided.
2. There are 174 addresses in Carey's shapefiles that could not be found in the output we generated based on DEC open data (title v and state). Some of them are caused by different ways of spelling in street names. such as 1 Avenue and first avenue. Some of them are due to failed geocoding, which is in the result of no address value in our output. There are also many records simply do not exist in the source data we used.
3. There 186 addresses only existing in our output.
https://nbviewer.jupyter.org/github/NYCPlanning/ceqr-app-data/blob/dec_notebook/notebook/DEC_Carey_comparison.ipynb

**Comparison between DECinfo locator and the output generated by open data**
1. There are 167 records existing in both datasets.
2. There are 79 records only existing in the output we generated based on DEC open data.
3. There are 76 records only existing in the [DECinfo Locator](https://gisservices.dec.ny.gov/gis/dil/)
4. Besides, the data from DECinfo Locator should be the same as the tables listed on the DEC website([title v](http://www.dec.ny.gov/dardata/boss/afs/issued_atv.html) and [state](http://www.dec.ny.gov/dardata/boss/afs/issued_asf.html)).
https://github.com/NYCPlanning/ceqr-app-data/blob/dec_notebook/notebook/DEC_Website_comparison.ipynb

**Comment by baolingz** [comment]
- [ ] Review non-geocoded records
  - [x] Handle intersections
  - [x] House number clean up, e.g., 458-460/464 NEPTUNE AVE
  - [x] Handle 3333 Broadway
  - [ ] Need to set up review process for remaining errors and a corrections file to apply to future updates
- [x] Remove unmapped records from geofile
- [ ] Make url clickable

**Comment by baolingz** [comment]
After removing permits that are outside NYC, missing `zipcode` and having the unclear address or having addresses out of range, there are 194 records got gecoded.
