### ISSUE TITLE
CEQR Air Quality: Manufacturing or processing facilities, boilers

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#14]
Source:
[DEP CATS Permits](https://data.cityofnewyork.us/Environment/CATS-Permits/f4rp-2kvy)

Steps:
- [x] load into recipes
- [x] only select records that have `CURRENT` in their status
- [x] Geocode

**Comment by baolingz** [comment]
- [x] Remove cancelled and expired permits?
- [x] Invalid values for BIN – wrong number of characters (only if geocoding failed?) **priority**
- [x] Geocoding errors **priority**
  - [x] Missing all of Staten Island, probably because STATENISLAND is one word in the borough field
  - [x] Basic address cleaning
    - [x] Remove quotes, e.g., Avenue ‘B’
    - [x] Remove parenthetical additions to street name, e.g., 91 STREET(RECTORY)
  - [x] Need to set up review process for remaining errors and a corrections file to apply to future updates
- [ ] Schema clean up
  - [x] Remove duplicate house and street name fields
  - [x] Include a cleaned up borough field.
  - [x] Remove grc field.
  - [x] Clean up field names (or create aliases)
- [x] Remove unmapped records from geofile **priority**

**Comment by AmandaDoyle** [comment]
Noted above, which tasks are priority tasks

**Comment by baolingz** [comment]
The number of characters for BIN value is correct, but it will return an empty string if nothing is returned by Geosupport

**Comment by baolingz** [comment]
Below are the DEP CATS permits that could be purged for air quality (confirmed with Cary):
- All permits that have statuses as CANCELLED
- All permits that have Application ID starting with ‘G’
- Permits that have Application ID starting with ‘CA’ + Request type as REGISTRATION or REGISTRATION INSPECTION
- Permits that have Application ID starting with ‘CA’ + Request type as WORK PERMIT + status as EXPIRED

After applying this logic, all permits are geocoded.

**Comment by baolingz** [comment]
```
SELECT * FROM dep_cats_permits.geo_rejects
WHERE status !~* 'CANCELLED'
AND LEFT(applicationid, 1) != 'G'
AND (LEFT(applicationid, 2) != 'CA' OR (requesttype != 'REGISTRATION' AND requesttype != 'REGISTRATION INSPECTION'))
AND (LEFT(applicationid, 2) != 'CA' OR requesttype != 'WORK PERMIT' OR status != 'EXPIRED')
;
```
