### ISSUE TITLE
CEQR Air Quality: DOT data sources

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#24]
Create data layer for each source.  We'll need to investigate to see what data are available on Open Data or other sources.

- [x] NYC DOT Traffic Cameras: https://www1.nyc.gov/html/dot/html/motorist/atis.shtml#traffic
- [x] NYS DOT Functional Class: https://gis3.dot.ny.gov/html5viewer/?viewer=FC
- [x] NYS Traffic Volume Data: https://gis3.dot.ny.gov/html5viewer/?viewer=tdv (some data points haven't been updated in 10 years so there might be a better source)
- [x] General Highway Data: https://www.dot.ny.gov/divisions/engineering/technical-services/highway-data-services/hdsb

**Comment by SPTKL** [comment]
+ camera_locations: https://511ny.org/map/mapIcons/Cameras
usage e.g.
camera id: 1cw00120w--30
footage: https://511ny.org/tooltip/Cameras/1cw00120w--30?lang=en-US

difference compare to https://webcams.nyctmc.org/ ?

Update: 
it's actually better because 511 has all NY state cameras, but we don't need that many
the nyctmc camera pop up is way easier than the tooltip implementation, not that the cid is captured at https://webcams.nyctmc.org/new-data.php?query=
e.g
https://webcams.nyctmc.org/google_popup.php?cid=274

**Comment by SPTKL** [comment]
+ functional class has issue with downloading complete set of records
+ after restricting to only download NYC data, gdal would get stuck at 80%
there should be a total of 33698 records, but only 28000 records are downloaded
https://gis3.dot.ny.gov/arcgis/rest/services/FC/MapServer/1/query?where=MUNICIPALITY_DESC%3D%27Brooklyn%27+or+MUNICIPALITY_DESC%3D%27Bronx%27+or+MUNICIPALITY_DESC%3D%27Staten+Island%27+or+MUNICIPALITY_DESC%3D%27Manhattan%27+or+MUNICIPALITY_DESC%3D%27Queens%27&f=html

Updates: 
+ resolved by changing f=geojson to f=json, and change projection using gdal
+ functional class loaded
